---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.59.1
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...

  - name: build
    image: ghcr.io/codestation/drone-docker
    settings:
      repo: registry.megpoid.dev/codestation/drone-kaniko
      tags:
        - latest
        - ${DRONE_TAG}
      registry: registry.megpoid.dev
      config:
        from_secret: registry_credentials
      build_args:
        - CI_COMMIT_TAG=${DRONE_TAG}
      build_args_from_env:
        - goproxy
      environment:
        goproxy:
          from_secret: goproxy_url
    when:
      event:
        - tag

trigger:
  event:
    - push
    - tag
