---
kind: pipeline
name: linux-amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.41.1
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...

  - name: build
    image: plugins/docker
    settings:
      repo: registry.megpoid.xyz/codestation/drone-kaniko
      tags: latest
      build_args:
        - CI_TAG=${DRONE_TAG}
        - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
        - BUILD_COMMIT_SHORT=${DRONE_COMMIT_SHA:0:8}
        - CI_BUILD_CREATED=${DRONE_BUILD_CREATED}
      registry: registry.megpoid.xyz
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push

trigger:
  branch:
    - master
