---
kind: pipeline
name: linux-amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.39.0
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...

  - name: build
    image: plugins/docker
    settings:
      repo: registry.megpoid.xyz/codestation/drone-kaniko
      tags: latest
      mirror: http://mirror:5000
      build_args:
        - CI_COMMIT_TAG=${DRONE_TAG}
        - CI_COMMIT_BRANCH=${DRONE_BRANCH}
        - CI_COMMIT_SHA=${DRONE_COMMIT_SHA}
        - CI_PIPELINE_CREATED_AT=${DRONE_BUILD_CREATED}
      registry: registry.megpoid.xyz
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push

trigger:
  branch:
    - master
