FROM golang:1.21-alpine AS gcompat

RUN apk fetch --no-cache musl-obstack libucontext gcompat musl \
    && mkdir /gcompat \
	&& tar -C /gcompat -xzf gcompat-*.apk \
    && tar -C /gcompat -xzf musl-obstack-*.apk \
	&& tar -C /gcompat -xzf libucontext-*.apk \
    && tar -C /gcompat -xzf musl-1*.apk \
    && rm -rf *.apk \
    && rm -rf /gcompat/.PKGINFO \
    && rm -rf /gcompat/.SIGN.RSA*

FROM gcr.io/kaniko-project/executor:v1.19.2-debug

COPY --from=gcompat /gcompat /
